#pragma once

//Game Parameters
#define SCREEN_WIDTH 1080
#define SCREEN_HEIGHT 1080
#define GRIDSIZE (SCREEN_WIDTH/24)
#define GAME_WIDTH SCREEN_WIDTH
#define GAME_HEIGHT (SCREEN_HEIGHT - GRIDSIZE * 2)
#define GRID_WIDTH  GAME_WIDTH/GRIDSIZE
#define GRID_HEIGHT GAME_HEIGHT/GRIDSIZE
#define TEXT_SIZE SCREEN_WIDTH/15
