#pragma once

//Game Parameters
#define SCREEN_WIDTH 480
#define SCREEN_HEIGHT 480
#define GAME_WIDTH SCREEN_WIDTH
#define GAME_HEIGHT (SCREEN_HEIGHT - 40)
#define GRIDSIZE 20
#define GRID_WIDTH  GAME_WIDTH/GRIDSIZE
#define GRID_HEIGHT GAME_HEIGHT/GRIDSIZE
